FROM golang:alpine
WORKDIR /app
COPY . .
RUN go build -o app ./cmd/app/main.go
RUN wget -O tailwind https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.1/tailwindcss-linux-x64 && \
    chmod +x tailwind && ./tailwind -i ./templates/input.css -o ./static/styles/output.css
RUN go install github.com/a-h/templ/cmd/templ@latest && \
    templ generate -path ./templates
RUN go build -o app ./cmd/app/main.go
CMD [ "./app" ]